services:
  mysql:
    image: mysql:8.0-oracle
    profiles:
      - with-mysql
    ports:
      - "23306:3306/tcp"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command:
      - "--skip-log-bin"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-hlocalhost", "-uroot", "-psecret"]
      start_period: 10s
      interval: 10s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "26379:6379/tcp"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      start_period: 5s
      interval: 10s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "21025:1025/tcp"
      - "28025:8025/tcp"
    volumes:
      - mailpit-data:/data
    environment:
      - MP_DATA_FILE=/data/mailpit.db

  minio:
    image: minio/minio:latest
    profiles:
      - with-minio
    ports:
      - "29000:9000/tcp"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    entrypoint: ["sh"]
    command: ["-c", "mkdir -p /data/${AWS_BUCKET} && minio server /data"]

  elasticsearch:
    image: elasticsearch:8.15.2
    profiles:
      - with-elasticsearch
    ports:
      - "29200:9200/tcp"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - bootstrap.memory_lock=true
      - action.destructive_requires_name=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  mysql-data:
    name: ${MYSQL_VOLUME}
    external: true
  redis-data:
    name: ${REDIS_VOLUME}
    external: true
  mailpit-data: {}
  minio-data:
    name: ${MINIO_VOLUME}
    external: true
  elasticsearch-data:
    name: ${ELASTICSEARCH_VOLUME}
    external: true
